name: On push
on:
  push:
    branches:
      - master

jobs:
  on_push:
    permissions:
      contents: write
    name: On Push
    uses: belonio/ci-workflows/.github/workflows/angular_package_workflow.yml@master
    secrets: inherit
    with:
      distPath: ./fake-dist
      nodeVersion: 18

