name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
        run: npx semantic-release
      - name: Code Coverage
        run: yarn coverage
